<?php
/*
 * contact_nocc module: Removes CC checkbox from Drupal 6 contact forms
 * Copyright (C) Wesley Tanaka <http://wtanaka.com>.  Licensed under
 * the GPL <http://gnu.org/copyleft/gpl.html>
 */
function contact_nocc_form_alter(&$form, $form_state, $form_id)
{
   if ($form_id == 'contact_mail_page' || $form_id == 'contact_mail_user')
   {
      if (isset($form['copy']))
      {
         $form['copy']['#type'] = 'value';
         unset($form['copy']['#title']);
      }
   }
}
